### PR TITLE
SS5

### PR DESCRIPTION
**Pull request by lerni**

### CODE REVIEW

**Comment by RVXD** [comment]
Hi Jonom, could you merge this PR?

**Comment by jonom** [comment]
Guess I forgot about this, sorry. @lerni & @RVXD have you both tested this module works just fine with SS5?

**Comment by lerni** [comment]
Yes using it quite a bit and all fine AFAIK 😃 If you could merge & tag a release, that would be awesome. Thanks!

**Comment by jonom** [comment]
Thanks. Tagged 4.2.2

**Pull request merged**
