### PR TITLE
ss4 update changes

### PR DESCRIPTION
**Pull request by RVXD**
Updated module to work with SilverStripe 4.

### CODE REVIEW

**Comment by jonom** [comment]
Thanks @RVXD! I will try to test this today.

**Comment by jonom** [comment]
Thanks for that @RVXD. I will follow up with another commit now to fix a couple of issues.

**Comment by jonom** [comment]
Tagged 3.0 for SS4 https://github.com/jonom/silverstripe-share-care/releases/tag/v3.0.0

**Comment by RVXD** [comment]
Great, thanks! Keep up the good work.

**Pull request merged**
